"""Initial phase 5.1 with naming convention

Revision ID: 38f878b66626
Revises: 
Create Date: 2026-07-30 04:41:56.942087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f878b66626'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_financeiras',
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categorias_financeiras'))
    )
    op.create_table('conciliacoes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'REJEITADO', name='statusconciliacao'), nullable=False),
    sa.Column('tipo_match', sa.Enum('UM_PARA_UM', 'UM_PARA_N', 'N_PARA_UM', 'N_PARA_M', name='tipomatch'), nullable=False),
    sa.Column('score_match', sa.Integer(), nullable=True),
    sa.Column('regra_utilizada', sa.String(length=100), nullable=True),
    sa.Column('matching_profile', sa.String(length=100), nullable=True),
    sa.Column('explainability_version', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_aprovacao', sa.DateTime(), nullable=True),
    sa.Column('aprovado_por', sa.String(length=100), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conciliacoes'))
    )
    op.create_table('empresas',
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('razao_social', sa.String(), nullable=True),
    sa.Column('nome_fantasia', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresas'))
    )
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_cnpj'), ['cnpj'], unique=True)

    op.create_table('execucoes_pipeline',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('CRIADA', 'ARQUIVOS_ANEXADOS', 'PROCESSANDO', 'CONCLUIDA', 'ERRO', name='statusexecucao'), nullable=False),
    sa.Column('matching_profile', sa.String(length=100), nullable=True),
    sa.Column('runtime_profile', sa.String(length=100), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('duracao_ms', sa.Float(), nullable=True),
    sa.Column('hashes_arquivos', sa.Text(), nullable=True),
    sa.Column('erro_codigo', sa.String(length=100), nullable=True),
    sa.Column('erro_mensagem', sa.Text(), nullable=True),
    sa.Column('erro_stacktrace', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execucoes_pipeline'))
    )
    op.create_table('fornecedores',
    sa.Column('cnpj_cpf', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('nome_normalizado', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fornecedores'))
    )
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fornecedores_cnpj_cpf'), ['cnpj_cpf'], unique=False)
        batch_op.create_index(batch_op.f('ix_fornecedores_nome_normalizado'), ['nome_normalizado'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'ANALISTA', 'AUDITOR', name='role'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios'))
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)

    op.create_table('conciliacao_explicacoes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conciliacao_id', sa.String(length=36), nullable=False),
    sa.Column('regra', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('peso', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('matching_profile', sa.String(length=100), nullable=True),
    sa.Column('explainability_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['conciliacao_id'], ['conciliacoes.id'], name=op.f('fk_conciliacao_explicacoes_conciliacao_id_conciliacoes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conciliacao_explicacoes'))
    )
    op.create_table('contas_bancarias',
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('banco', sa.String(), nullable=True),
    sa.Column('agencia', sa.String(), nullable=True),
    sa.Column('conta', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_contas_bancarias_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contas_bancarias'))
    )
    op.create_table('contas_contabeis',
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('codigo_contabil', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('natureza', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_contas_contabeis_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contas_contabeis'))
    )
    with op.batch_alter_table('contas_contabeis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contas_contabeis_codigo_contabil'), ['codigo_contabil'], unique=False)

    op.create_table('importacoes_arquivo',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execucao_id', sa.String(length=36), nullable=False),
    sa.Column('nome_original', sa.String(), nullable=False),
    sa.Column('tipo', sa.Enum('DESPESA', 'EXTRATO', 'RAZAO', name='tipoarquivo'), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('hash_sha256', sa.String(), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=100), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes_pipeline.id'], name=op.f('fk_importacoes_arquivo_execucao_id_execucoes_pipeline')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_importacoes_arquivo'))
    )
    op.create_table('projetos',
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('codigo_externo', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_projetos_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projetos'))
    )
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projetos_codigo_externo'), ['codigo_externo'], unique=False)

    op.create_table('despesas',
    sa.Column('fornecedor_id', sa.UUID(), nullable=True),
    sa.Column('projeto_id', sa.UUID(), nullable=True),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=True),
    sa.Column('id_uuid_origem', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_financeiras.id'], name=op.f('fk_despesas_categoria_id_categorias_financeiras')),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], name=op.f('fk_despesas_fornecedor_id_fornecedores')),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], name=op.f('fk_despesas_projeto_id_projetos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_despesas'))
    )
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_despesas_id_uuid_origem'), ['id_uuid_origem'], unique=False)

    op.create_table('extratos_bancarios',
    sa.Column('conta_bancaria_id', sa.UUID(), nullable=True),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_fim', sa.Date(), nullable=True),
    sa.Column('saldo_inicial', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('saldo_final', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['conta_bancaria_id'], ['contas_bancarias.id'], name=op.f('fk_extratos_bancarios_conta_bancaria_id_contas_bancarias')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extratos_bancarios'))
    )
    op.create_table('lancamentos_contabeis',
    sa.Column('conta_contabil_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('historico', sa.String(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tipo', sa.Enum('D', 'C', name='tipomovimentacao'), nullable=True),
    sa.Column('lote', sa.String(), nullable=True),
    sa.Column('chave_origem_sci', sa.String(), nullable=True),
    sa.Column('conta_contrapartida', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['conta_contabil_id'], ['contas_contabeis.id'], name=op.f('fk_lancamentos_contabeis_conta_contabil_id_contas_contabeis')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lancamentos_contabeis'))
    )
    with op.batch_alter_table('lancamentos_contabeis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lancamentos_contabeis_chave_origem_sci'), ['chave_origem_sci'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_contabeis_data'), ['data'], unique=False)

    op.create_table('movimentacoes_bancarias',
    sa.Column('extrato_id', sa.UUID(), nullable=True),
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('historico', sa.String(), nullable=True),
    sa.Column('descricao_original', sa.String(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('tipo', sa.Enum('D', 'C', name='tipomovimentacao'), nullable=True),
    sa.Column('codigo_cp', sa.String(), nullable=True),
    sa.Column('linha_origem', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['extrato_id'], ['extratos_bancarios.id'], name=op.f('fk_movimentacoes_bancarias_extrato_id_extratos_bancarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimentacoes_bancarias'))
    )
    with op.batch_alter_table('movimentacoes_bancarias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentacoes_bancarias_codigo_cp'), ['codigo_cp'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_bancarias_data'), ['data'], unique=False)

    op.create_table('parcelas_despesa',
    sa.Column('despesa_id', sa.UUID(), nullable=True),
    sa.Column('numero_parcela', sa.Integer(), nullable=True),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_vencimento', sa.Date(), nullable=True),
    sa.Column('data_pagamento_esperada', sa.Date(), nullable=True),
    sa.Column('id_parcela_origem', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['despesa_id'], ['despesas.id'], name=op.f('fk_parcelas_despesa_despesa_id_despesas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parcelas_despesa'))
    )
    with op.batch_alter_table('parcelas_despesa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parcelas_despesa_id_parcela_origem'), ['id_parcela_origem'], unique=False)

    op.create_table('candidate_evaluation_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execucao_id', sa.String(length=36), nullable=False),
    sa.Column('movimentacao_id', sa.UUID(), nullable=False),
    sa.Column('parcela_id', sa.UUID(), nullable=True),
    sa.Column('motivo_descarte', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes_pipeline.id'], name=op.f('fk_candidate_evaluation_log_execucao_id_execucoes_pipeline')),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacoes_bancarias.id'], name=op.f('fk_candidate_evaluation_log_movimentacao_id_movimentacoes_bancarias')),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas_despesa.id'], name=op.f('fk_candidate_evaluation_log_parcela_id_parcelas_despesa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_evaluation_log'))
    )
    op.create_table('conciliacoes_itens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conciliacao_id', sa.String(length=36), nullable=False),
    sa.Column('parcela_id', sa.String(length=36), nullable=True),
    sa.Column('movimentacao_id', sa.String(length=36), nullable=True),
    sa.Column('lancamento_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['conciliacao_id'], ['conciliacoes.id'], name=op.f('fk_conciliacoes_itens_conciliacao_id_conciliacoes')),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos_contabeis.id'], name=op.f('fk_conciliacoes_itens_lancamento_id_lancamentos_contabeis')),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacoes_bancarias.id'], name=op.f('fk_conciliacoes_itens_movimentacao_id_movimentacoes_bancarias')),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas_despesa.id'], name=op.f('fk_conciliacoes_itens_parcela_id_parcelas_despesa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conciliacoes_itens'))
    )
    op.create_table('documentos_fiscais',
    sa.Column('parcela_id', sa.UUID(), nullable=True),
    sa.Column('numero_nf', sa.String(), nullable=True),
    sa.Column('chave_acesso', sa.String(), nullable=True),
    sa.Column('valor_nf', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas_despesa.id'], name=op.f('fk_documentos_fiscais_parcela_id_parcelas_despesa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documentos_fiscais'))
    )
    op.create_table('match_candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execucao_id', sa.String(length=36), nullable=False),
    sa.Column('movimentacao_id', sa.UUID(), nullable=False),
    sa.Column('parcela_id', sa.UUID(), nullable=True),
    sa.Column('score_total', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE_REVISAO', 'REJEITADO_PELO_MOTOR', 'APROVADO', name='statuscandidato'), nullable=False),
    sa.Column('motivo_descarte', sa.Text(), nullable=True),
    sa.Column('explanation_snapshot', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes_pipeline.id'], name=op.f('fk_match_candidates_execucao_id_execucoes_pipeline')),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacoes_bancarias.id'], name=op.f('fk_match_candidates_movimentacao_id_movimentacoes_bancarias')),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas_despesa.id'], name=op.f('fk_match_candidates_parcela_id_parcelas_despesa')),
    sa.ForeignKeyConstraint(['reviewed_by'], ['usuarios.id'], name=op.f('fk_match_candidates_reviewed_by_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_candidates'))
    )
    op.create_table('pagamentos',
    sa.Column('parcela_id', sa.UUID(), nullable=True),
    sa.Column('movimentacao_id', sa.UUID(), nullable=True),
    sa.Column('valor_pago', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('juros', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('desconto', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacoes_bancarias.id'], name=op.f('fk_pagamentos_movimentacao_id_movimentacoes_bancarias')),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas_despesa.id'], name=op.f('fk_pagamentos_parcela_id_parcelas_despesa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagamentos'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamentos')
    op.drop_table('match_candidates')
    op.drop_table('documentos_fiscais')
    op.drop_table('conciliacoes_itens')
    op.drop_table('candidate_evaluation_log')
    with op.batch_alter_table('parcelas_despesa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcelas_despesa_id_parcela_origem'))

    op.drop_table('parcelas_despesa')
    with op.batch_alter_table('movimentacoes_bancarias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentacoes_bancarias_data'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_bancarias_codigo_cp'))

    op.drop_table('movimentacoes_bancarias')
    with op.batch_alter_table('lancamentos_contabeis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamentos_contabeis_data'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_contabeis_chave_origem_sci'))

    op.drop_table('lancamentos_contabeis')
    op.drop_table('extratos_bancarios')
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_despesas_id_uuid_origem'))

    op.drop_table('despesas')
    with op.batch_alter_table('projetos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projetos_codigo_externo'))

    op.drop_table('projetos')
    op.drop_table('importacoes_arquivo')
    with op.batch_alter_table('contas_contabeis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contas_contabeis_codigo_contabil'))

    op.drop_table('contas_contabeis')
    op.drop_table('contas_bancarias')
    op.drop_table('conciliacao_explicacoes')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fornecedores_nome_normalizado'))
        batch_op.drop_index(batch_op.f('ix_fornecedores_cnpj_cpf'))

    op.drop_table('fornecedores')
    op.drop_table('execucoes_pipeline')
    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_cnpj'))

    op.drop_table('empresas')
    op.drop_table('conciliacoes')
    op.drop_table('categorias_financeiras')
    # ### end Alembic commands ###
