"""auto_add_missing_tables

Revision ID: daaa97b535d9
Revises: e20f4eb97abc
Create Date: 2026-08-09 01:10:44.658527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'daaa97b535d9'
down_revision: Union[str, Sequence[str], None] = 'e20f4eb97abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas_financeiras',
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.Enum('BANCO', 'CAIXA_ESPECIE', 'CARTAO_CREDITO', name='tipocontafinanceira'), nullable=False),
    sa.Column('banco_codigo', sa.String(length=10), nullable=True),
    sa.Column('agencia', sa.String(length=20), nullable=True),
    sa.Column('numero_conta', sa.String(length=30), nullable=True),
    sa.Column('saldo_inicial', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contas_financeiras'))
    )
    op.create_table('client_schema_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('file_signature', sa.String(length=255), nullable=False),
    sa.Column('mapping_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_client_schema_mappings_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_client_schema_mappings'))
    )
    with op.batch_alter_table('client_schema_mappings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_schema_mappings_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_client_schema_mappings_file_signature'), ['file_signature'], unique=False)

    op.create_table('receitas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execucao_id', sa.String(length=36), nullable=True),
    sa.Column('cliente_nome', sa.String(length=255), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('data_recebimento', sa.Date(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('conta_destino', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes_pipeline.id'], name=op.f('fk_receitas_execucao_id_execucoes_pipeline')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receitas'))
    )
    op.create_table('staging_registro',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('execucao_id', sa.String(length=50), nullable=True),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.Enum('RECEITA', 'DESPESA', 'EXTRATO', 'DINHEIRO', name='tipostaging'), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('entidade_nome', sa.String(length=255), nullable=True),
    sa.Column('cnpj_cpf', sa.String(length=30), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('conta_origem', sa.String(length=100), nullable=True),
    sa.Column('conta_destino', sa.String(length=100), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('processado', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_staging_registro_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes_pipeline.id'], name=op.f('fk_staging_registro_execucao_id_execucoes_pipeline')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staging_registro'))
    )
    with op.batch_alter_table('staging_registro', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_staging_registro_execucao_id'), ['execucao_id'], unique=False)

    op.create_table('candidate_evaluation_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('execucao_id', sa.String(length=36), nullable=False),
    sa.Column('movimentacao_id', sa.UUID(), nullable=False),
    sa.Column('parcela_id', sa.UUID(), nullable=True),
    sa.Column('lancamento_id', sa.UUID(), nullable=True),
    sa.Column('regra', sa.String(length=100), nullable=False),
    sa.Column('motivo_descarte', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes_pipeline.id'], name=op.f('fk_candidate_evaluation_logs_execucao_id_execucoes_pipeline')),
    sa.ForeignKeyConstraint(['lancamento_id'], ['lancamentos_contabeis.id'], name=op.f('fk_candidate_evaluation_logs_lancamento_id_lancamentos_contabeis')),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacoes_bancarias.id'], name=op.f('fk_candidate_evaluation_logs_movimentacao_id_movimentacoes_bancarias')),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas_despesa.id'], name=op.f('fk_candidate_evaluation_logs_parcela_id_parcelas_despesa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_evaluation_logs'))
    )
    op.drop_table('candidate_evaluation_log')
    with op.batch_alter_table('execucoes_pipeline', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.UUID(), nullable=True))
        batch_op.add_column(sa.Column('tax_summary', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_execucoes_pipeline_empresa_id_empresas'), 'empresas', ['empresa_id'], ['id'])

    with op.batch_alter_table('match_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lancamento_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_match_candidates_lancamento_id_lancamentos_contabeis'), 'lancamentos_contabeis', ['lancamento_id'], ['id'])

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_usuarios_empresa_id_empresas'), 'empresas', ['empresa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_usuarios_empresa_id_empresas'), type_='foreignkey')
        batch_op.drop_column('empresa_id')

    with op.batch_alter_table('match_candidates', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_match_candidates_lancamento_id_lancamentos_contabeis'), type_='foreignkey')
        batch_op.drop_column('lancamento_id')

    with op.batch_alter_table('execucoes_pipeline', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_execucoes_pipeline_empresa_id_empresas'), type_='foreignkey')
        batch_op.drop_column('tax_summary')
        batch_op.drop_column('empresa_id')

    op.create_table('candidate_evaluation_log',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('execucao_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('movimentacao_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('parcela_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('motivo_descarte', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('origem_sistema', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes_pipeline.id'], name=op.f('fk_candidate_evaluation_log_execucao_id_execucoes_pipeline')),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacoes_bancarias.id'], name=op.f('fk_candidate_evaluation_log_movimentacao_id_movimentaco_8503')),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas_despesa.id'], name=op.f('fk_candidate_evaluation_log_parcela_id_parcelas_despesa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_evaluation_log'))
    )
    op.drop_table('candidate_evaluation_logs')
    with op.batch_alter_table('staging_registro', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_staging_registro_execucao_id'))

    op.drop_table('staging_registro')
    op.drop_table('receitas')
    with op.batch_alter_table('client_schema_mappings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_schema_mappings_file_signature'))
        batch_op.drop_index(batch_op.f('ix_client_schema_mappings_empresa_id'))

    op.drop_table('client_schema_mappings')
    op.drop_table('contas_financeiras')
    # ### end Alembic commands ###
