"""add_execucao_id_to_financial_entities

Revision ID: e20f4eb97abc
Revises: 38f878b66626
Create Date: 2026-07-30 21:12:43.075846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e20f4eb97abc'
down_revision: Union[str, Sequence[str], None] = '38f878b66626'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execucao_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_despesas_execucao_id_execucoes_pipeline'), 'execucoes_pipeline', ['execucao_id'], ['id'])

    with op.batch_alter_table('lancamentos_contabeis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execucao_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_lancamentos_contabeis_execucao_id_execucoes_pipeline'), 'execucoes_pipeline', ['execucao_id'], ['id'])

    with op.batch_alter_table('movimentacoes_bancarias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execucao_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_movimentacoes_bancarias_execucao_id_execucoes_pipeline'), 'execucoes_pipeline', ['execucao_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movimentacoes_bancarias', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_movimentacoes_bancarias_execucao_id_execucoes_pipeline'), type_='foreignkey')
        batch_op.drop_column('execucao_id')

    with op.batch_alter_table('lancamentos_contabeis', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_lancamentos_contabeis_execucao_id_execucoes_pipeline'), type_='foreignkey')
        batch_op.drop_column('execucao_id')

    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_despesas_execucao_id_execucoes_pipeline'), type_='foreignkey')
        batch_op.drop_column('execucao_id')

    # ### end Alembic commands ###
