"""refactor_domain_legacy_to_financeiro

Revision ID: f2fb07577434
Revises: daaa97b535d9
Create Date: 2026-08-11 03:26:58.330817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2fb07577434'
down_revision: Union[str, Sequence[str], None] = 'daaa97b535d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas_fiscal',
    sa.Column('empresa_id', sa.String(length=36), nullable=False),
    sa.Column('regime_tributario', sa.Enum('SIMPLES_NACIONAL', 'LUCRO_PRESUMIDO', 'LUCRO_REAL', 'RET', 'ISENTO', name='regimetributario'), nullable=False),
    sa.Column('codigo_cnae_principal', sa.String(length=10), nullable=True),
    sa.Column('inscricao_estadual', sa.String(length=30), nullable=True),
    sa.Column('inscricao_municipal', sa.String(length=30), nullable=True),
    sa.Column('municipio_ibge', sa.String(length=7), nullable=True),
    sa.Column('municipio_nome', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('optante_simples', sa.Boolean(), nullable=True),
    sa.Column('contribuinte_icms', sa.Boolean(), nullable=True),
    sa.Column('sujeito_retencao_iss', sa.Boolean(), nullable=True),
    sa.Column('sujeito_retencao_inss', sa.Boolean(), nullable=True),
    sa.Column('sistema_contabil_destino', sa.String(length=50), nullable=True),
    sa.Column('config_exportacao', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresas_fiscal'))
    )
    with op.batch_alter_table('empresas_fiscal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_empresas_fiscal_empresa_id'), ['empresa_id'], unique=True)

    op.create_table('regras_fiscais_municipio',
    sa.Column('municipio_ibge', sa.String(length=7), nullable=False),
    sa.Column('municipio_nome', sa.String(length=100), nullable=False),
    sa.Column('uf', sa.String(length=2), nullable=False),
    sa.Column('aliquota_iss_construcao', sa.String(length=10), nullable=True),
    sa.Column('aliquota_iss_empreitada', sa.String(length=10), nullable=True),
    sa.Column('aliquota_iss_subempreitada', sa.String(length=10), nullable=True),
    sa.Column('aliquota_iss_projetos', sa.String(length=10), nullable=True),
    sa.Column('retencao_iss_obrigatoria_pj', sa.Boolean(), nullable=True),
    sa.Column('retencao_iss_obrigatoria_pf', sa.Boolean(), nullable=True),
    sa.Column('valor_minimo_retencao_iss', sa.String(length=15), nullable=True),
    sa.Column('codigo_tributario_municipal', sa.String(length=20), nullable=True),
    sa.Column('link_legislacao', sa.String(length=255), nullable=True),
    sa.Column('data_vigencia', sa.String(length=10), nullable=True),
    sa.Column('fonte', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regras_fiscais_municipio'))
    )
    with op.batch_alter_table('regras_fiscais_municipio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regras_fiscais_municipio_municipio_ibge'), ['municipio_ibge'], unique=True)

    op.create_table('tabela_irrf',
    sa.Column('tipo_beneficiario', sa.String(length=5), nullable=False),
    sa.Column('natureza_pagamento', sa.String(length=100), nullable=False),
    sa.Column('codigo_darf', sa.String(length=10), nullable=False),
    sa.Column('aliquota', sa.String(length=8), nullable=False),
    sa.Column('deducao_parcela', sa.String(length=15), nullable=True),
    sa.Column('valor_minimo_retencao', sa.String(length=15), nullable=True),
    sa.Column('base_legal', sa.String(length=100), nullable=True),
    sa.Column('vigencia_inicio', sa.String(length=10), nullable=False),
    sa.Column('vigencia_fim', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tabela_irrf'))
    )
    op.create_table('apuracoes_fiscais',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('competencia', sa.String(length=7), nullable=False),
    sa.Column('faturamento_total', sa.Float(), nullable=False),
    sa.Column('imposto_devido', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_apuracoes_fiscais_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_apuracoes_fiscais'))
    )
    with op.batch_alter_table('apuracoes_fiscais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_apuracoes_fiscais_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('movimentacoes_financeiras',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('ENTRADA', 'SAIDA', name='tipomovimentacao'), nullable=False),
    sa.Column('data_transacao', sa.Date(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('descricao_extrato', sa.String(length=255), nullable=False),
    sa.Column('documento_banco', sa.String(length=100), nullable=True),
    sa.Column('conciliada', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_movimentacoes_financeiras_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimentacoes_financeiras'))
    )
    with op.batch_alter_table('movimentacoes_financeiras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentacoes_financeiras_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('obras',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('codigo_interno', sa.String(length=50), nullable=True),
    sa.Column('codigo_cno', sa.String(length=20), nullable=True),
    sa.Column('codigo_cei', sa.String(length=20), nullable=True),
    sa.Column('endereco_obra', sa.String(length=255), nullable=True),
    sa.Column('municipio_ibge', sa.String(length=7), nullable=True),
    sa.Column('municipio_nome', sa.String(length=100), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.Column('tipo', sa.Enum('RESIDENCIAL', 'COMERCIAL', 'INDUSTRIAL', 'INFRAESTRUTURA', 'REFORMA', 'MISTA', name='tipoobra'), nullable=False),
    sa.Column('status', sa.Enum('PLANEJAMENTO', 'EM_ANDAMENTO', 'PARALISADA', 'CONCLUIDA', 'ENTREGUE', name='statusobra'), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=True),
    sa.Column('data_entrega_prevista', sa.Date(), nullable=True),
    sa.Column('data_conclusao_real', sa.Date(), nullable=True),
    sa.Column('patrimonio_afetacao', sa.Boolean(), nullable=False),
    sa.Column('regime_tributario', sa.Enum('RET', 'NORMAL', 'ISENTO', name='regimetributarioobra'), nullable=False),
    sa.Column('orcamento_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('custo_incorrido_total', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('receita_contratada_total', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('percentual_avanco_fisico', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('conta_bancaria_afetacao', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_obras_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_obras'))
    )
    with op.batch_alter_table('obras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obras_codigo_cno'), ['codigo_cno'], unique=True)
        batch_op.create_index(batch_op.f('ix_obras_codigo_interno'), ['codigo_interno'], unique=False)
        batch_op.create_index(batch_op.f('ix_obras_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('plano_de_contas',
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('codigo_contabil', sa.String(length=30), nullable=False),
    sa.Column('conta_pai_id', sa.UUID(), nullable=True),
    sa.Column('nivel', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('descricao_reduzida', sa.String(length=50), nullable=True),
    sa.Column('grupo', sa.Enum('ATIVO', 'PASSIVO', 'PATRIMONIO_LIQUIDO', 'RECEITA', 'DESPESA', 'CUSTO', 'RESULTADO', name='grupoconta'), nullable=False),
    sa.Column('natureza', sa.Enum('DEVEDORA', 'CREDORA', name='naturezaconta'), nullable=False),
    sa.Column('tipo', sa.Enum('SINTETICA', 'ANALITICA', name='tipoconta'), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('aceita_lancamentos', sa.Boolean(), nullable=False),
    sa.Column('conta_caixa_banco', sa.Boolean(), nullable=True),
    sa.Column('conta_resultado', sa.Boolean(), nullable=True),
    sa.Column('codigo_dominio', sa.String(length=20), nullable=True),
    sa.Column('codigo_alterdata', sa.String(length=20), nullable=True),
    sa.Column('codigo_sped', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['conta_pai_id'], ['plano_de_contas.id'], name=op.f('fk_plano_de_contas_conta_pai_id_plano_de_contas')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_plano_de_contas_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plano_de_contas'))
    )
    with op.batch_alter_table('plano_de_contas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plano_de_contas_codigo_contabil'), ['codigo_contabil'], unique=False)

    op.create_table('templates_lancamento',
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('natureza_operacao', sa.String(length=30), nullable=True),
    sa.Column('tipo_documento', sa.String(length=20), nullable=True),
    sa.Column('regime_tributario', sa.String(length=30), nullable=True),
    sa.Column('partidas_json', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_templates_lancamento_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_templates_lancamento'))
    )
    op.create_table('detalhes_impostos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('apuracao_id', sa.String(length=36), nullable=False),
    sa.Column('tipo_imposto', sa.Enum('IRPJ', 'CSLL', 'PIS', 'COFINS', 'ISS', 'INSS', 'SIMPLES_NACIONAL', 'MEI_DAS', name='tipoimposto'), nullable=False),
    sa.Column('base_de_calculo', sa.Float(), nullable=False),
    sa.Column('aliquota', sa.Float(), nullable=False),
    sa.Column('valor_apurado', sa.Float(), nullable=False),
    sa.Column('valor_retido', sa.Float(), nullable=False),
    sa.Column('valor_a_pagar', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['apuracao_id'], ['apuracoes_fiscais.id'], name=op.f('fk_detalhes_impostos_apuracao_id_apuracoes_fiscais')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detalhes_impostos'))
    )
    op.create_table('documentos_fiscais_v2',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('obra_id', sa.UUID(), nullable=True),
    sa.Column('fornecedor_id', sa.UUID(), nullable=True),
    sa.Column('execucao_id', sa.String(length=36), nullable=True),
    sa.Column('tipo', sa.Enum('NFE', 'NFSE', 'CTE', 'RPA', 'FATURA', 'RECIBO', 'BOLETO', name='tipodocumentofiscal'), nullable=False),
    sa.Column('natureza_operacao', sa.Enum('MATERIAL', 'SERVICO', 'EMPREITADA', 'SUBEMPREITADA', 'LOCACAO_EQUIPAMENTO', 'ALUGUEL', 'CONCESSIONARIA', 'FINANCEIRO', 'FOLHA', name='naturezaoperacao'), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'APROVADO', 'PAGO', 'CANCELADO', 'REJEITADO', 'AGUARDANDO_NF', name='statusdocumentofiscal'), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=True),
    sa.Column('serie', sa.String(length=5), nullable=True),
    sa.Column('chave_acesso', sa.String(length=44), nullable=True),
    sa.Column('codigo_verificacao', sa.String(length=20), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('data_entrada', sa.Date(), nullable=True),
    sa.Column('data_competencia', sa.Date(), nullable=True),
    sa.Column('emitente_cnpj_cpf', sa.String(length=20), nullable=True),
    sa.Column('emitente_nome', sa.String(length=255), nullable=True),
    sa.Column('emitente_municipio_ibge', sa.String(length=7), nullable=True),
    sa.Column('emitente_municipio_nome', sa.String(length=100), nullable=True),
    sa.Column('emitente_inscricao_municipal', sa.String(length=30), nullable=True),
    sa.Column('valor_bruto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_desconto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_outras_deducoes', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_base_calculo', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('iss_aliquota', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('iss_valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('iss_retido_fonte', sa.Boolean(), nullable=False),
    sa.Column('iss_municipio_recolhimento', sa.String(length=7), nullable=True),
    sa.Column('inss_aliquota', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('inss_valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('inss_retido', sa.Boolean(), nullable=False),
    sa.Column('inss_artigo_retencao', sa.String(length=50), nullable=True),
    sa.Column('ir_aliquota', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('ir_valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('ir_retido', sa.Boolean(), nullable=False),
    sa.Column('ir_codigo_darf', sa.String(length=10), nullable=True),
    sa.Column('pis_valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('cofins_valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('csll_valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('csrf_retido', sa.Boolean(), nullable=False),
    sa.Column('total_retencoes', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('valor_liquido_pagar', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('cfop', sa.String(length=5), nullable=True),
    sa.Column('ncm', sa.String(length=10), nullable=True),
    sa.Column('codigo_servico_lc116', sa.String(length=10), nullable=True),
    sa.Column('discriminacao_servicos', sa.Text(), nullable=True),
    sa.Column('importado_via', sa.String(length=50), nullable=True),
    sa.Column('xml_original', sa.Text(), nullable=True),
    sa.Column('observacoes_fiscais', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_documentos_fiscais_v2_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes_pipeline.id'], name=op.f('fk_documentos_fiscais_v2_execucao_id_execucoes_pipeline')),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], name=op.f('fk_documentos_fiscais_v2_fornecedor_id_fornecedores')),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], name=op.f('fk_documentos_fiscais_v2_obra_id_obras')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documentos_fiscais_v2'))
    )
    with op.batch_alter_table('documentos_fiscais_v2', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_fiscais_v2_chave_acesso'), ['chave_acesso'], unique=True)
        batch_op.create_index(batch_op.f('ix_documentos_fiscais_v2_emitente_cnpj_cpf'), ['emitente_cnpj_cpf'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_fiscais_v2_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_fiscais_v2_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_fiscais_v2_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_fiscais_v2_obra_id'), ['obra_id'], unique=False)

    op.create_table('mapeamentos_contas_referenciais',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('conta_interna_id', sa.UUID(), nullable=False),
    sa.Column('codigo_conta_referencial', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['conta_interna_id'], ['plano_de_contas.id'], name=op.f('fk_mapeamentos_contas_referenciais_conta_interna_id_plano_de_contas')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_mapeamentos_contas_referenciais_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mapeamentos_contas_referenciais'))
    )
    with op.batch_alter_table('mapeamentos_contas_referenciais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mapeamentos_contas_referenciais_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('obrigacoes_acessorias_jobs',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('SPED_ECD', 'SPED_ECF', 'DEFIS', name='tipoobrigacao'), nullable=False),
    sa.Column('ano_calendario', sa.String(length=4), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'PROCESSANDO', 'CONCLUIDO', 'ERRO', 'ERRO_VALIDACAO', name='statusobrigacao'), nullable=False),
    sa.Column('arquivo_url', sa.String(length=500), nullable=True),
    sa.Column('log_erros', sa.Text(), nullable=True),
    sa.Column('solicitado_por', sa.String(length=36), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_obrigacoes_acessorias_jobs_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['solicitado_por'], ['usuarios.id'], name=op.f('fk_obrigacoes_acessorias_jobs_solicitado_por_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_obrigacoes_acessorias_jobs'))
    )
    with op.batch_alter_table('obrigacoes_acessorias_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_obrigacoes_acessorias_jobs_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('periodos_contabeis',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('ano_mes', sa.String(length=7), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'FECHADO', name='statusperiodo'), nullable=False),
    sa.Column('fechado_por', sa.String(length=36), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_periodos_contabeis_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['fechado_por'], ['usuarios.id'], name=op.f('fk_periodos_contabeis_fechado_por_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_periodos_contabeis'))
    )
    with op.batch_alter_table('periodos_contabeis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_periodos_contabeis_ano_mes'), ['ano_mes'], unique=False)
        batch_op.create_index(batch_op.f('ix_periodos_contabeis_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('subempreiteiros',
    sa.Column('obra_id', sa.UUID(), nullable=False),
    sa.Column('fornecedor_id', sa.UUID(), nullable=False),
    sa.Column('tipo_contrato', sa.String(length=30), nullable=True),
    sa.Column('valor_contrato', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('data_contrato', sa.Date(), nullable=True),
    sa.Column('objeto_contrato', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], name=op.f('fk_subempreiteiros_fornecedor_id_fornecedores')),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], name=op.f('fk_subempreiteiros_obra_id_obras')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subempreiteiros'))
    )
    op.create_table('workspace_members',
    sa.Column('usuario_id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALISTA', 'AUDITOR', name='role'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_workspace_members_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_workspace_members_usuario_id_usuarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_members'))
    )
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_members_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workspace_members_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('lancamentos_cabecalhos',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('data_competencia', sa.Date(), nullable=False),
    sa.Column('historico_padrao', sa.String(length=255), nullable=False),
    sa.Column('numero_lote', sa.String(length=100), nullable=False),
    sa.Column('modulo_origem', sa.Enum('FINANCEIRO', 'FISCAL', 'FOLHA', 'MANUAL', name='moduloorigem'), nullable=False),
    sa.Column('status', sa.Enum('RASCUNHO', 'CONFIRMADO', 'EXPORTADO', 'CANCELADO', name='statuslancamento'), nullable=False),
    sa.Column('documento_fiscal_id', sa.UUID(), nullable=True),
    sa.Column('obra_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['documento_fiscal_id'], ['documentos_fiscais_v2.id'], name=op.f('fk_lancamentos_cabecalhos_documento_fiscal_id_documentos_fiscais_v2')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_lancamentos_cabecalhos_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], name=op.f('fk_lancamentos_cabecalhos_obra_id_obras')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lancamentos_cabecalhos'))
    )
    with op.batch_alter_table('lancamentos_cabecalhos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lancamentos_cabecalhos_data_competencia'), ['data_competencia'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_cabecalhos_documento_fiscal_id'), ['documento_fiscal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_cabecalhos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_cabecalhos_numero_lote'), ['numero_lote'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_cabecalhos_obra_id'), ['obra_id'], unique=False)

    op.create_table('parcelas_documento_fiscal',
    sa.Column('documento_id', sa.UUID(), nullable=False),
    sa.Column('numero_parcela', sa.String(length=10), nullable=False),
    sa.Column('valor_parcela', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=30), nullable=True),
    sa.Column('movimentacao_financeira_id', sa.UUID(), nullable=True),
    sa.Column('id_externo_erp', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['documento_id'], ['documentos_fiscais_v2.id'], name=op.f('fk_parcelas_documento_fiscal_documento_id_documentos_fiscais_v2')),
    sa.ForeignKeyConstraint(['movimentacao_financeira_id'], ['movimentacoes_financeiras.id'], name=op.f('fk_parcelas_documento_fiscal_movimentacao_financeira_id_movimentacoes_financeiras')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parcelas_documento_fiscal'))
    )
    with op.batch_alter_table('parcelas_documento_fiscal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parcelas_documento_fiscal_documento_id'), ['documento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parcelas_documento_fiscal_id_externo_erp'), ['id_externo_erp'], unique=False)

    op.create_table('titulos_financeiros',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('obra_id', sa.UUID(), nullable=True),
    sa.Column('documento_fiscal_id', sa.String(length=36), nullable=True),
    sa.Column('tipo', sa.Enum('PAGAR', 'RECEBER', name='tipotitulo'), nullable=False),
    sa.Column('status', sa.Enum('ABERTO', 'VENCIDO', 'PARCIAL', 'LIQUIDADO', 'CANCELADO', name='statustitulo'), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('fornecedor_cliente_nome', sa.String(length=255), nullable=True),
    sa.Column('fornecedor_cliente_cnpj_cpf', sa.String(length=20), nullable=True),
    sa.Column('valor_nominal', sa.Float(), nullable=False),
    sa.Column('valor_pago', sa.Float(), nullable=True),
    sa.Column('data_emissao', sa.Date(), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('gerado_automaticamente', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['documento_fiscal_id'], ['documentos_fiscais_v2.id'], name=op.f('fk_titulos_financeiros_documento_fiscal_id_documentos_fiscais_v2')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_titulos_financeiros_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], name=op.f('fk_titulos_financeiros_obra_id_obras')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_titulos_financeiros'))
    )
    with op.batch_alter_table('titulos_financeiros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_titulos_financeiros_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_titulos_financeiros_obra_id'), ['obra_id'], unique=False)

    op.create_table('conciliacoes_financeiras',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('titulo_id', sa.String(length=36), nullable=False),
    sa.Column('movimentacao_id', sa.String(length=36), nullable=False),
    sa.Column('valor_conciliado', sa.Float(), nullable=False),
    sa.Column('data_conciliacao', sa.Date(), nullable=False),
    sa.Column('match_automatico', sa.Boolean(), nullable=True),
    sa.Column('confianca_match', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_conciliacoes_financeiras_empresa_id_empresas')),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacoes_financeiras.id'], name=op.f('fk_conciliacoes_financeiras_movimentacao_id_movimentacoes_financeiras')),
    sa.ForeignKeyConstraint(['titulo_id'], ['titulos_financeiros.id'], name=op.f('fk_conciliacoes_financeiras_titulo_id_titulos_financeiros')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conciliacoes_financeiras'))
    )
    with op.batch_alter_table('conciliacoes_financeiras', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conciliacoes_financeiras_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('partidas_itens',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('cabecalho_id', sa.UUID(), nullable=False),
    sa.Column('conta_contabil_id', sa.UUID(), nullable=False),
    sa.Column('centro_custo_id', sa.UUID(), nullable=True),
    sa.Column('natureza', sa.Enum('DEBITO', 'CREDITO', name='tipopartida'), nullable=False),
    sa.Column('valor', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('historico_complementar', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('origem_sistema', sa.String(), nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cabecalho_id'], ['lancamentos_cabecalhos.id'], name=op.f('fk_partidas_itens_cabecalho_id_lancamentos_cabecalhos')),
    sa.ForeignKeyConstraint(['conta_contabil_id'], ['plano_de_contas.id'], name=op.f('fk_partidas_itens_conta_contabil_id_plano_de_contas')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_partidas_itens_empresa_id_empresas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partidas_itens'))
    )
    with op.batch_alter_table('partidas_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partidas_itens_cabecalho_id'), ['cabecalho_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partidas_itens_conta_contabil_id'), ['conta_contabil_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partidas_itens_empresa_id'), ['empresa_id'], unique=False)

    with op.batch_alter_table('parcelas_despesa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcelas_despesa_id_parcela_origem'))

    op.drop_table('parcelas_despesa')
    op.drop_table('extratos_bancarios')
    with op.batch_alter_table('lancamentos_contabeis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamentos_contabeis_chave_origem_sci'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_contabeis_data'))

    op.drop_table('lancamentos_contabeis')
    with op.batch_alter_table('movimentacoes_bancarias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentacoes_bancarias_codigo_cp'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_bancarias_data'))

    op.drop_table('movimentacoes_bancarias')
    op.drop_table('documentos_fiscais')
    op.drop_table('pagamentos')
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_despesas_id_uuid_origem'))

    op.drop_table('despesas')
    with op.batch_alter_table('candidate_evaluation_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movimentacao_financeira_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('titulo_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('lancamento_cabecalho_id', sa.String(length=36), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_candidate_evaluation_logs_lancamento_id_lancamentos__9767'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_candidate_evaluation_logs_parcela_id_parcelas_despesa'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_candidate_evaluation_logs_movimentacao_id_movimentac_bcc8'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_candidate_evaluation_logs_movimentacao_financeira_id_movimentacoes_financeiras'), 'movimentacoes_financeiras', ['movimentacao_financeira_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_candidate_evaluation_logs_lancamento_cabecalho_id_lancamentos_cabecalhos'), 'lancamentos_cabecalhos', ['lancamento_cabecalho_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_candidate_evaluation_logs_titulo_id_titulos_financeiros'), 'titulos_financeiros', ['titulo_id'], ['id'])
        batch_op.drop_column('movimentacao_id')
        batch_op.drop_column('lancamento_id')
        batch_op.drop_column('parcela_id')

    with op.batch_alter_table('conciliacoes_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('titulo_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('movimentacao_financeira_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('lancamento_cabecalho_id', sa.String(length=36), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_conciliacoes_itens_movimentacao_id_movimentacoes_bancarias'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_conciliacoes_itens_parcela_id_parcelas_despesa'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_conciliacoes_itens_lancamento_id_lancamentos_contabeis'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_conciliacoes_itens_lancamento_cabecalho_id_lancamentos_cabecalhos'), 'lancamentos_cabecalhos', ['lancamento_cabecalho_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_conciliacoes_itens_titulo_id_titulos_financeiros'), 'titulos_financeiros', ['titulo_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_conciliacoes_itens_movimentacao_financeira_id_movimentacoes_financeiras'), 'movimentacoes_financeiras', ['movimentacao_financeira_id'], ['id'])
        batch_op.drop_column('movimentacao_id')
        batch_op.drop_column('lancamento_id')
        batch_op.drop_column('parcela_id')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('import_config', sa.JSON(), nullable=True))

    with op.batch_alter_table('match_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movimentacao_financeira_id', sa.String(length=36), nullable=False))
        batch_op.add_column(sa.Column('titulo_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('lancamento_cabecalho_id', sa.String(length=36), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_match_candidates_movimentacao_id_movimentacoes_bancarias'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_match_candidates_parcela_id_parcelas_despesa'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_match_candidates_lancamento_id_lancamentos_contabeis'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_match_candidates_titulo_id_titulos_financeiros'), 'titulos_financeiros', ['titulo_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_match_candidates_lancamento_cabecalho_id_lancamentos_cabecalhos'), 'lancamentos_cabecalhos', ['lancamento_cabecalho_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_match_candidates_movimentacao_financeira_id_movimentacoes_financeiras'), 'movimentacoes_financeiras', ['movimentacao_financeira_id'], ['id'])
        batch_op.drop_column('movimentacao_id')
        batch_op.drop_column('lancamento_id')
        batch_op.drop_column('parcela_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match_candidates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parcela_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lancamento_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('movimentacao_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_match_candidates_movimentacao_financeira_id_movimentacoes_financeiras'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_match_candidates_lancamento_cabecalho_id_lancamentos_cabecalhos'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_match_candidates_titulo_id_titulos_financeiros'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_match_candidates_lancamento_id_lancamentos_contabeis'), 'lancamentos_contabeis', ['lancamento_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_match_candidates_parcela_id_parcelas_despesa'), 'parcelas_despesa', ['parcela_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_match_candidates_movimentacao_id_movimentacoes_bancarias'), 'movimentacoes_bancarias', ['movimentacao_id'], ['id'])
        batch_op.drop_column('lancamento_cabecalho_id')
        batch_op.drop_column('titulo_id')
        batch_op.drop_column('movimentacao_financeira_id')

    with op.batch_alter_table('empresas', schema=None) as batch_op:
        batch_op.drop_column('import_config')

    with op.batch_alter_table('conciliacoes_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parcela_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lancamento_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('movimentacao_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_conciliacoes_itens_movimentacao_financeira_id_movimentacoes_financeiras'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_conciliacoes_itens_titulo_id_titulos_financeiros'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_conciliacoes_itens_lancamento_cabecalho_id_lancamentos_cabecalhos'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_conciliacoes_itens_lancamento_id_lancamentos_contabeis'), 'lancamentos_contabeis', ['lancamento_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_conciliacoes_itens_parcela_id_parcelas_despesa'), 'parcelas_despesa', ['parcela_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_conciliacoes_itens_movimentacao_id_movimentacoes_bancarias'), 'movimentacoes_bancarias', ['movimentacao_id'], ['id'])
        batch_op.drop_column('lancamento_cabecalho_id')
        batch_op.drop_column('movimentacao_financeira_id')
        batch_op.drop_column('titulo_id')

    with op.batch_alter_table('candidate_evaluation_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parcela_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('lancamento_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('movimentacao_id', sa.UUID(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_candidate_evaluation_logs_titulo_id_titulos_financeiros'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_candidate_evaluation_logs_lancamento_cabecalho_id_lancamentos_cabecalhos'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_candidate_evaluation_logs_movimentacao_financeira_id_movimentacoes_financeiras'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_candidate_evaluation_logs_movimentacao_id_movimentac_bcc8'), 'movimentacoes_bancarias', ['movimentacao_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_candidate_evaluation_logs_parcela_id_parcelas_despesa'), 'parcelas_despesa', ['parcela_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_candidate_evaluation_logs_lancamento_id_lancamentos__9767'), 'lancamentos_contabeis', ['lancamento_id'], ['id'])
        batch_op.drop_column('lancamento_cabecalho_id')
        batch_op.drop_column('titulo_id')
        batch_op.drop_column('movimentacao_financeira_id')

    op.create_table('despesas',
    sa.Column('fornecedor_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('projeto_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('categoria_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('valor_total', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('data_emissao', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('id_uuid_origem', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('origem_sistema', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('execucao_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_financeiras.id'], name=op.f('fk_despesas_categoria_id_categorias_financeiras')),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes_pipeline.id'], name=op.f('fk_despesas_execucao_id_execucoes_pipeline')),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], name=op.f('fk_despesas_fornecedor_id_fornecedores')),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], name=op.f('fk_despesas_projeto_id_projetos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_despesas'))
    )
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_despesas_id_uuid_origem'), ['id_uuid_origem'], unique=False)

    op.create_table('pagamentos',
    sa.Column('parcela_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('movimentacao_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('valor_pago', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('juros', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('desconto', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('data_pagamento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('origem_sistema', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['movimentacao_id'], ['movimentacoes_bancarias.id'], name=op.f('fk_pagamentos_movimentacao_id_movimentacoes_bancarias')),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas_despesa.id'], name=op.f('fk_pagamentos_parcela_id_parcelas_despesa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pagamentos'))
    )
    op.create_table('documentos_fiscais',
    sa.Column('parcela_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('numero_nf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chave_acesso', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('valor_nf', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('origem_sistema', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parcela_id'], ['parcelas_despesa.id'], name=op.f('fk_documentos_fiscais_parcela_id_parcelas_despesa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documentos_fiscais'))
    )
    op.create_table('movimentacoes_bancarias',
    sa.Column('extrato_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('historico', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('descricao_original', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('valor', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('tipo', postgresql.ENUM('D', 'C', name='tipomovimentacao'), autoincrement=False, nullable=True),
    sa.Column('codigo_cp', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('linha_origem', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('origem_sistema', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('execucao_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes_pipeline.id'], name=op.f('fk_movimentacoes_bancarias_execucao_id_execucoes_pipeline')),
    sa.ForeignKeyConstraint(['extrato_id'], ['extratos_bancarios.id'], name=op.f('fk_movimentacoes_bancarias_extrato_id_extratos_bancarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimentacoes_bancarias'))
    )
    with op.batch_alter_table('movimentacoes_bancarias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentacoes_bancarias_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_bancarias_codigo_cp'), ['codigo_cp'], unique=False)

    op.create_table('lancamentos_contabeis',
    sa.Column('conta_contabil_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('historico', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('valor', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('tipo', postgresql.ENUM('D', 'C', name='tipomovimentacao'), autoincrement=False, nullable=True),
    sa.Column('lote', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('chave_origem_sci', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('conta_contrapartida', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('origem_sistema', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('execucao_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conta_contabil_id'], ['contas_contabeis.id'], name=op.f('fk_lancamentos_contabeis_conta_contabil_id_contas_contabeis')),
    sa.ForeignKeyConstraint(['execucao_id'], ['execucoes_pipeline.id'], name=op.f('fk_lancamentos_contabeis_execucao_id_execucoes_pipeline')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lancamentos_contabeis'))
    )
    with op.batch_alter_table('lancamentos_contabeis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lancamentos_contabeis_data'), ['data'], unique=False)
        batch_op.create_index(batch_op.f('ix_lancamentos_contabeis_chave_origem_sci'), ['chave_origem_sci'], unique=False)

    op.create_table('extratos_bancarios',
    sa.Column('conta_bancaria_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('data_inicio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_fim', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('saldo_inicial', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('saldo_final', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('origem_sistema', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conta_bancaria_id'], ['contas_bancarias.id'], name=op.f('fk_extratos_bancarios_conta_bancaria_id_contas_bancarias')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extratos_bancarios'))
    )
    op.create_table('parcelas_despesa',
    sa.Column('despesa_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('numero_parcela', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valor', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('data_vencimento', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_pagamento_esperada', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('id_parcela_origem', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('origem_sistema', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arquivo_origem', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['despesa_id'], ['despesas.id'], name=op.f('fk_parcelas_despesa_despesa_id_despesas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_parcelas_despesa'))
    )
    with op.batch_alter_table('parcelas_despesa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parcelas_despesa_id_parcela_origem'), ['id_parcela_origem'], unique=False)

    with op.batch_alter_table('partidas_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partidas_itens_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_partidas_itens_conta_contabil_id'))
        batch_op.drop_index(batch_op.f('ix_partidas_itens_cabecalho_id'))

    op.drop_table('partidas_itens')
    with op.batch_alter_table('conciliacoes_financeiras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conciliacoes_financeiras_empresa_id'))

    op.drop_table('conciliacoes_financeiras')
    with op.batch_alter_table('titulos_financeiros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_titulos_financeiros_obra_id'))
        batch_op.drop_index(batch_op.f('ix_titulos_financeiros_empresa_id'))

    op.drop_table('titulos_financeiros')
    with op.batch_alter_table('parcelas_documento_fiscal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcelas_documento_fiscal_id_externo_erp'))
        batch_op.drop_index(batch_op.f('ix_parcelas_documento_fiscal_documento_id'))

    op.drop_table('parcelas_documento_fiscal')
    with op.batch_alter_table('lancamentos_cabecalhos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lancamentos_cabecalhos_obra_id'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_cabecalhos_numero_lote'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_cabecalhos_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_cabecalhos_documento_fiscal_id'))
        batch_op.drop_index(batch_op.f('ix_lancamentos_cabecalhos_data_competencia'))

    op.drop_table('lancamentos_cabecalhos')
    with op.batch_alter_table('workspace_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_members_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_workspace_members_empresa_id'))

    op.drop_table('workspace_members')
    op.drop_table('subempreiteiros')
    with op.batch_alter_table('periodos_contabeis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_periodos_contabeis_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_periodos_contabeis_ano_mes'))

    op.drop_table('periodos_contabeis')
    with op.batch_alter_table('obrigacoes_acessorias_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obrigacoes_acessorias_jobs_empresa_id'))

    op.drop_table('obrigacoes_acessorias_jobs')
    with op.batch_alter_table('mapeamentos_contas_referenciais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mapeamentos_contas_referenciais_empresa_id'))

    op.drop_table('mapeamentos_contas_referenciais')
    with op.batch_alter_table('documentos_fiscais_v2', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_fiscais_v2_obra_id'))
        batch_op.drop_index(batch_op.f('ix_documentos_fiscais_v2_numero'))
        batch_op.drop_index(batch_op.f('ix_documentos_fiscais_v2_fornecedor_id'))
        batch_op.drop_index(batch_op.f('ix_documentos_fiscais_v2_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_documentos_fiscais_v2_emitente_cnpj_cpf'))
        batch_op.drop_index(batch_op.f('ix_documentos_fiscais_v2_chave_acesso'))

    op.drop_table('documentos_fiscais_v2')
    op.drop_table('detalhes_impostos')
    op.drop_table('templates_lancamento')
    with op.batch_alter_table('plano_de_contas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plano_de_contas_codigo_contabil'))

    op.drop_table('plano_de_contas')
    with op.batch_alter_table('obras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_obras_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_obras_codigo_interno'))
        batch_op.drop_index(batch_op.f('ix_obras_codigo_cno'))

    op.drop_table('obras')
    with op.batch_alter_table('movimentacoes_financeiras', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentacoes_financeiras_empresa_id'))

    op.drop_table('movimentacoes_financeiras')
    with op.batch_alter_table('apuracoes_fiscais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apuracoes_fiscais_empresa_id'))

    op.drop_table('apuracoes_fiscais')
    op.drop_table('tabela_irrf')
    with op.batch_alter_table('regras_fiscais_municipio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regras_fiscais_municipio_municipio_ibge'))

    op.drop_table('regras_fiscais_municipio')
    with op.batch_alter_table('empresas_fiscal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_empresas_fiscal_empresa_id'))

    op.drop_table('empresas_fiscal')
    # ### end Alembic commands ###
